### ISSUE TITLE
Where is the base address ?

### ISSUE THREAD

**Issue by GaspardCulis** [spookybear0/gd-addresses#24]
Hi, 

Never done modding or looked that deep in an app memory, but in your docs you always speak about the **"base"** address, where do you find this ? My goal is to extract the game state directly from the process memory, any advice ?

Cheers

**Comment by spookybear0** [comment]
The base process is where it begins in memory, it depends how you are modding the game to get it.

In C++, you can get it while attached as a thread in a dll with `reinterpret_cast<uintptr_t>(GetModuleHandle(0));`.
